# Generated by Django 4.2.6 on 2023-10-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='title',
            field=models.TextField(),
        ),
    ]
