# Generated by Django 4.2.6 on 2023-10-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_bookmodel_author_alter_bookmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
