# Generated by Django 4.2.6 on 2023-10-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_alter_bookmodel_author_alter_bookmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='year',
            field=models.CharField(null=True),
        ),
    ]
